let Controller = {};
Controller.AuthController = require('./AuthController');
Controller.SettingCon = require('./SettingCon');
Controller.UpDownCheckingCon = require('./UpDownCheckingCon');
Controller.SearchingCon = require('./SearchingCon');
Controller.HackedDNSDetectingCon = require('./HackedDNSDetectingCon');
Controller.ExportingCon = require('./ExportingCon');
Controller.OtherCon = require('./OtherCon');
Controller.CredentialManagerCon = require('./CredentialManagerCon');
Controller.CoinMinerDetectingCon = require('./CoinMinerDetectingCon');
module.exports = Controller;
//# sourceMappingURL=Controller.js.map