const express = require('express');
const router = express.Router();
const AuthRouter = require('./AuthRouter');
const SettingRouter = require('./SettingRouter');
const UpDownCheckingRouter = require('./UpDownCheckingRouter');
const SearchingRouter = require('./SearchingRouter');
const ExportingRouter = require('./ExportingRouter');
const HackedDNSDetectingRouter = require('./HackedDNSDetectingRouter');
const OtherRouter = require('./OtherRouter');
const CredentialManagerRouter = require('./CredentialManagerRouter');
router.use('/api/v1/', UpDownCheckingRouter);
router.use('/api/v1/', AuthRouter);
router.use('/api/v1/', SettingRouter);
router.use('/api/v1/', SearchingRouter);
router.use('/api/v1/', HackedDNSDetectingRouter);
router.use('/api/v1/', ExportingRouter);
router.use('/api/v1/', OtherRouter);
router.use('/api/v1/', CredentialManagerRouter);
module.exports = router;
//# sourceMappingURL=Router.js.map